### ISSUE TITLE
"Пepeнoc" лиц пepcoнaжeй из Gothic I в Gothic II и oбpaтнo.

### ISSUE THREAD

**Issue by Kor-Angar** [Kor-Angar/G1#4]
В Г1 в отличие от Г2а ЛИЦО задается двумя числами т.к. ТЕКСТУРА ЛИЦА взаимосвязана с ПАЛИТРОЙ, которая также привязана к ТЕКСТУРЕ ТЕЛА НПЦ, т.е в Г1 у одной ТЕКСТУРЫ ЛИЦА и ТЕКСТУРЫ ТЕЛА должна быть общая ПАЛИТРА.
В Г2а перестали использовать нумерацию ПАЛИТРЫ, переведя все исчисление только на нумерацию ТЕКСТУР, т.е. в Г2а ПАЛИТРА всегда имеет нулевое значение как и ТЕКСТУРА ТЕЛА, поэтому для любой ТЕКСТУРЫ ТЕЛА, независмо от оттенка кожи (ПАЛИТРЫ), можно подставить любую ТЕКСТУРУ ЛИЦА.

Для более лучшего понимания:

Задание внешности в Г1
Mdl_SetVisualBody (НПЦ, МОДЕЛЬ_ТЕЛА, ТЕКСТУРА_ТЕЛА, ПАЛИТРА, МОДЕЛЬ_ГОЛОВЫ, ТЕКСТУРА_ЛИЦА, ТЕКСТУРА_ЗУБОВ, ДОСПЕХИ);

Задание внешности в Г2а
B_SetNpcVisual(НПЦ, ПОЛ, МОДЕЛЬ_ГОЛОВЫ, ТЕКСТУРА_ЛИЦА, ТЕКСТУРА_ТЕЛА, ДОСПЕХИ);

Как видно, в Г2а многое было упрощено через внешнюю функцию B_SetNpcVisual, далее ниже представлены примеры задания внешности Торуса в Г1 и Г2а.
Еще ниже представлена ТАБЛИЦА КОНСТАНТ, которые используются в Г2а для задания ТЕКСТУРЫ ЛИЦА, хотя вместо констант можно писать и простые числа.
И в самом низу идут две ТАБЛИЦЫ ПЕРЕКОДИРОВКИ лиц из формата Г1 в Г2а и наоборот. Лица сектантов, которые могут понадобиться в Г2а отсутствуют - их нужно будет извлечь из Г1 и пронумеровать самостоятельно.

- - - - - - - -

Готика 1
(Торус)
Mdl_SetVisualBody (self,"hum_body_Naked0",0,3,"Hum_Head_Fighter", 12,0,GRD_ARMOR_H);

Итак в данном случае у Торуса в Г1 ТЕКСТУРА ЛИЦА имеет номер 12, с ПАЛИТРОЙ номер 3. В таблице перекодировки (Г1 в Г2а) находим, что в Г2а это соответствует текстуре номер 4

- - - - - - - -

Готика 2
(Торус)
B_SetNpcVisual(self,MALE,"Hum_Head_Fighter",Face_B_Thorus,BodyTex_B,ITAR_Thorus_ Addon);

Теперь попробуем перекодировать из формата Г2а в формат Г1.
В данном случае у Торуса ТЕКСТУРА ЛИЦА имеет константу Face_B_Thorus, что равно из приведенной ниже таблице чилсу 4 (см. пример выше), теперь ищем в таблице перекодировки (Г2а в Г1), соответствующую ТЕКСТУРУ Г2а и получаем для Г1 ТЕКСТУР 12 и ПАЛИТРУ 3

***

Г1 => Г2а
Номер ТЕКСТУРЫ Г1|Номер ПАЛИТРЫ Г1 => Номер ТЕКСТУРЫ Г2а
0|0 => 55
0|1 => 86
0|2 => 126
1|0 => 49
1|1 => 118 !
1|2 => 127
1|3 => 132
2|0 => 45
2|1 => 89
2|2 => 128
2|3 => 133
3|0 => 56
3|1 => 10
3|2 => 120
3|3 => 129
4|0 => 42
4|1 => 91
4|2 => 40
4|3 => 130
5|0 => 43
5|1 => 27
5|2 => 8
5|3 => 131
6|0 => 44
6|1 => 2

6|3 => 134
7|0 => 52
7|1 => 107
7|3 => 12
8|0 => 53
8|1 => 81
8|2 => 124
8|3 => 135
9|0 => 54
9|1 => 18
9|2 => 15
9|3 => 136
10|0 => 57
10|1 => 58
10|2 => 121
10|3 => 28
11|0 => 51
11|1 => 32
11|2 => 122
11|3 => 11
12|0 => 47
12|1 => 63
12|2 => 123
12|3 => 4
13|0 => 41
13|1 => 72

13|3 => 17
14|0 => 48
14|1 => 114
14|2 => 29

15|1 => 115
15|2 => 30
16|0 => 39
16|1 => 73
16|2 => 125
17|0 => 19
17|1 => 74
18|0 => 46
18|1 => 7
19|1 => 62
20|0 => 50

35|1 => 75
36|1 => 34
37|1 => 35
38|1 => 36
39|1 => 16
40|1 => 90
41|1 => 118
42|1 => 92
43|1 => 93
44|1 => 94
45|1 => 64
46|1 => 76
47|1 => 77
48|1 => 78
49|1 => 79
50|1 => 95
51|1 => 26
52|1 => 96
53|1 => 21
54|1 => 97
55|1 => 80
56|1 => 37
57|1 => 3
58|1 => 98

67|1 => 99
68|1 => 100
69|1 => 101
70|1 => 102
71|1 => 103
72|1 => 104
73|1 => 105
74|1 => 106

76|1 => 6
77|1 => 116
78|1 => 60
79|1 => 1
80|1 => 108
81|1 => 33
82|1 => 13
83|1 => 9
84|1 => 5
85|1 => 0

87|1 => 14
88|1 => 20
89|1 => 25
90|1 => 117
91|1 => 23
92|1 => 82
93|1 => 83
94|1 => 84
95|1 => 85
96 - отсутствует
97|1 => 38
98|1 => 119
99|1 => 24
100|1 => 109
101|1 => 110
102|1 => 65
103|1 => 61
104|1 => 66
105|1 => 111
106|1 => 67
107|1 => 68
108|1 => 87
109|1 => 22
110|1 => 59
111|1 => 69
112|1 => 88
113|1 => 112
114|1 => 113
115|1 => 70
116|1 => 71
117|1 => 31

***
// ------- Gesichter fьr Mдnner ------
const int Face_N_Gomez = 0 ;
const int Face_N_Scar = 1 ;
const int Face_N_Raven = 2 ;
const int Face_N_Bullit = 3 ; //zu lieb!
const int Face_B_Thorus = 4 ;
const int Face_N_Corristo = 5 ;
const int Face_N_Milten = 6 ;
const int Face_N_Bloodwyn = 7 ; //zu lieb!
const int Face_L_Scatty = 8 ;
const int Face_N_YBerion = 9 ;
const int Face_N_CoolPock = 10 ;
const int Face_B_CorAngar = 11 ;
const int Face_B_Saturas = 12 ;
const int Face_N_Xardas = 13 ;
const int Face_N_Lares = 14 ;
const int Face_L_Ratford = 15 ;
const int Face_N_Drax = 16 ; //Buster
const int Face_B_Gorn = 17 ;
const int Face_N_Player = 18 ;
const int Face_P_Lester = 19 ;
const int Face_N_Lee = 20 ;
const int Face_N_Torlof = 21 ;
const int Face_N_Mud = 22 ;
const int Face_N_Ricelord = 23 ;
const int Face_N_Horatio = 24 ;
const int Face_N_Richter = 25 ;
const int Face_N_Cipher_neu = 26 ;
const int Face_N_Homer = 27 ; //Headmesh thief
const int Face_B_Cavalorn = 28 ;
const int Face_L_Ian = 29 ;
const int Face_L_Diego = 30 ;
const int Face_N_MadPsi = 31 ;
const int Face_N_Bartholo = 32 ;
const int Face_N_Snaf = 33 ;
const int Face_N_Mordrag = 34 ;
const int Face_N_Lefty = 35 ;
const int Face_N_Wolf = 36 ;
const int Face_N_Fingers = 37 ;
const int Face_N_Whistler = 38 ;
const int Face_P_Gilbert = 39 ;
const int Face_L_Jackal = 40 ;

//Pale
const int Face_P_ToughBald = 41 ;
const int Face_P_Tough_Drago = 42 ;
const int Face_P_Tough_Torrez = 43 ;
const int Face_P_Tough_Rodriguez = 44 ;
const int Face_P_ToughBald_Nek = 45 ;
const int Face_P_NormalBald = 46 ;
const int Face_P_Normal01 = 47 ;
const int Face_P_Normal02 = 48 ;
const int Face_P_Normal_Fletcher = 49 ;
const int Face_P_Normal03 = 50 ;
const int Face_P_NormalBart01 = 51 ;
const int Face_P_NormalBart_Cronos = 52 ;
const int Face_P_NormalBart_Nefarius= 53 ;
const int Face_P_NormalBart_Riordian= 54 ;
const int Face_P_OldMan_Gravo = 55 ;
const int Face_P_Weak_Cutter = 56 ;
const int Face_P_Weak_Ulf_Wohlers = 57 ;

//Normal
const int Face_N_Important_Arto = 58 ;
const int Face_N_ImportantGrey = 59 ;
const int Face_N_ImportantOld = 60 ;
const int Face_N_Tough_Lee_дhnlich = 61 ;
const int Face_N_Tough_Skip = 62 ;
const int Face_N_ToughBart01 = 63 ;
const int Face_N_Tough_Okyl = 64 ;
const int Face_N_Normal01 = 65 ;
const int Face_N_Normal_Cord = 66 ;
const int Face_N_Normal_Olli_Kahn = 67 ;
const int Face_N_Normal02 = 68 ;
const int Face_N_Normal_Spassvogel = 69 ;
const int Face_N_Normal03 = 70 ;
const int Face_N_Normal04 = 71 ;
const int Face_N_Normal05 = 72 ;
const int Face_N_Normal_Stone = 73 ;
const int Face_N_Normal06 = 74 ;
const int Face_N_Normal_Erpresser = 75 ;
const int Face_N_Normal07 = 76 ;
const int Face_N_Normal_Blade = 77 ;
const int Face_N_Normal08 = 78 ;
const int Face_N_Normal14 = 79 ;
const int Face_N_Normal_Sly = 80 ;
const int Face_N_Normal16 = 81 ;
const int Face_N_Normal17 = 82 ;
const int Face_N_Normal18 = 83 ;
const int Face_N_Normal19 = 84 ;
const int Face_N_Normal20 = 85 ;
const int Face_N_NormalBart01 = 86 ;
const int Face_N_NormalBart02 = 87 ;
const int Face_N_NormalBart03 = 88 ;
const int Face_N_NormalBart04 = 89 ;
const int Face_N_NormalBart05 = 90 ;
const int Face_N_NormalBart06 = 91 ;
const int Face_N_NormalBart_Senyan = 92 ;
const int Face_N_NormalBart08 = 93 ;
const int Face_N_NormalBart09 = 94 ;
const int Face_N_NormalBart10 = 95 ;
const int Face_N_NormalBart11 = 96 ;
const int Face_N_NormalBart12 = 97 ;
const int Face_N_NormalBart_Dexter = 98 ;
const int Face_N_NormalBart_Graham = 99 ;
const int Face_N_NormalBart_Dusty = 100 ;
const int Face_N_NormalBart16 = 101 ;
const int Face_N_NormalBart17 = 102 ;
const int Face_N_NormalBart_Huno = 103 ;
const int Face_N_NormalBart_Grim = 104 ;
const int Face_N_NormalBart20 = 105 ;
const int Face_N_NormalBart21 = 106 ;
const int Face_N_NormalBart22 = 107 ;
const int Face_N_OldBald_Jeremiah = 108 ;
const int Face_N_Weak_Ulbert = 109 ;
const int Face_N_Weak_BaalNetbek = 110 ;
const int Face_N_Weak_Herek = 111 ;
const int Face_N_Weak04 = 112 ;
const int Face_N_Weak05 = 113 ;
const int Face_N_Weak_Orry = 114 ;
const int Face_N_Weak_Asghan = 115 ;
const int Face_N_Weak_Markus_Kark = 116 ;
const int Face_N_Weak_Cipher_alt = 117 ;
const int Face_N_NormalBart_Swiney = 118 ;
const int Face_N_Weak12 = 119 ;

//Latinos
const int Face_L_ToughBald01 = 120 ;
const int Face_L_Tough01 = 121 ;
const int Face_L_Tough02 = 122 ;
const int Face_L_Tough_Santino = 123 ;
const int Face_L_ToughBart_Quentin = 124 ;
const int Face_L_Normal_GorNaBar = 125 ;
const int Face_L_NormalBart01 = 126 ;
const int Face_L_NormalBart02 = 127 ;
const int Face_L_NormalBart_Rufus = 128 ;

//Black
const int Face_B_ToughBald = 129 ;
const int Face_B_Tough_Pacho = 130 ;
const int Face_B_Tough_Silas = 131 ;
const int Face_B_Normal01 = 132 ;
const int Face_B_Normal_Kirgo = 133 ;
const int Face_B_Normal_Sharky = 134 ;
const int Face_B_Normal_Orik = 135 ;
const int Face_B_Normal_Kharim = 136 ;

// ------ Gesichter fьr Frauen ------

const int FaceBabe_N_BlackHair = 137 ;
const int FaceBabe_N_Blondie = 138 ;
const int FaceBabe_N_BlondTattoo = 139 ;
const int FaceBabe_N_PinkHair = 140 ;
const int FaceBabe_L_Charlotte = 141 ;
const int FaceBabe_B_RedLocks = 142 ;
const int FaceBabe_N_HairAndCloth = 143 ;
//
const int FaceBabe_N_WhiteCloth = 144 ;
const int FaceBabe_N_GreyCloth = 145 ;
const int FaceBabe_N_Brown = 146 ;
const int FaceBabe_N_VlkBlonde = 147 ;
const int FaceBabe_N_BauBlonde = 148 ;
const int FaceBabe_N_YoungBlonde = 149 ;
const int FaceBabe_N_OldBlonde = 150 ;
const int FaceBabe_P_MidBlonde = 151 ;
const int FaceBabe_N_MidBauBlonde = 152 ;
const int FaceBabe_N_OldBrown = 153 ;
const int FaceBabe_N_Lilo = 154 ;
const int FaceBabe_N_Hure = 155 ;
const int FaceBabe_N_Anne = 156 ;
const int FaceBabe_B_RedLocks2 = 157 ;
const int FaceBabe_L_Charlotte2 = 158 ;

//-----------------ADD ON---------------------------------
const int Face_N_Fortuno = 159;

//Piraten
const int Face_P_Greg = 160;
const int Face_N_Pirat01 = 161;
const int Face_N_ZombieMud = 162;

**Comment by dosinabox** [comment]
'''
insert fh
'''

**Comment by dosinabox** [comment]
А ещё в Г2 осталась только одна текстура зубов. В Г1 их было четыре. В рамках неофициального обновления Г2НВ было бы неплохо вернуть переходящим персонажам их зубы из первой части.

**Comment by Kor-Angar** [comment]
Это Ларс. У него в Г1 был золотой зуб 😀 больше неодного не знаю 😀8:48, 29 марта 2020 г., dosinabox <notifications@github.com>:
А ещё в Г2 осталась только одна текстура зубов. В Г1 их было четыре. В рамках неофициального обновления Г2НВ было бы неплохо вернуть переходящим персонажам их зубы из первой части.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Kor-Angar** [comment]
Пираньи лентяи. так всё по уму сделали в Готики 1, а в Готики 2 нехватило сил это дело модернизовать :-(
